### PR TITLE
Make various make targets symmetrical and usable from the top level.

### PR DESCRIPTION
**Pull request by jordanhubbard**
This essentially describes (and fixes) the problem we're discussing in https://github.com/elixir-nx/nx/issues/294

### CODE REVIEW

**Comment by jordanhubbard** [comment]
Also, QQ:  What audience *is* the all target in the exla directory for?  Internal developers who have some type of environment (variable) setup in advance or is it actually just an alias for `mix compile` with another, internal, target taking over from "all"?  I ask only because targets like clean, all, and install are generally considered "public API" and they should therefore just work with reasonable defaults.

**Comment by seanmor5** [comment]
Ah yes this makes sense to me now!

So both `all` and `clean` are only ever intended to be invoked by `elixir_make` on calls to `mix compile` and `mix clean` respectively. They're the default targets `elixir_make` looks for in these cases, although I'm not sure if that can be changed. I do see where the confusion is coming in with respect to the environment variables coming out of nowhere. An easy fix is to set them from within the Makefile rather than on waiting for Elixir to do it, although I can't think of a reason to compile without mix, unless you had something in mind?

As for the PR, for completeness it might make sense to add:

`cd nx && mix compile` as well. But we have plans to split the repository up, so any adjustment to the build process in this case should probably be made directly to EXLA rather than at this level. I will defer to @josevalim on this one :)

**Comment by jordanhubbard** [comment]
Please see updated commit - this covers the concerns you raised and rounds out the makefile's default target coverage a bit more.

**Comment by josevalim** [comment]
This was meant to be used only internally but adding some conveniences doesn’t hurt. Thank you!

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Pull request merged**
