### PR TITLE
Improvements to `from_numpy` and `from_numpy_archive`

### PR DESCRIPTION
**Pull request by laursisask**
See commit messages for more

### CODE REVIEW

**Comment by josevalim** [comment]
Thanks @laursisask, this looks great!

Can you please add the changes to the return format in this PR too? That's because we will merge this only once the work on v0.5 starts. So having everything in a single PR will avoid merge conflicts down the road. Thank you! :heart:

**Comment by laursisask** [comment]
> Thanks @laursisask, this looks great!
> 
> Can you please add the changes to the return format in this PR too? That's because we will merge this only once the work on v0.5 starts. So having everything in a single PR will avoid merge conflicts down the road. Thank you! ❤️

Added the change to the return format. Also added a few tests for these functions, currently they were not tested at all.

**Comment by josevalim** [comment]
Awesome work, I will include this as part of v0.5.

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Pull request merged**
