### PR TITLE
Format Nx

### PR DESCRIPTION
**Pull request by Benjamin-Philip**

### CODE REVIEW

**Comment by Benjamin-Philip** [comment]
This should fix the failing tests, both on main and my previous PR.

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Comment by Benjamin-Philip** [comment]
> green_heart blue_heart purple_heart yellow_heart heart

Do you have a webhook to comment the hearts? You seem to comment the hearts for all PRs, and it seems to me that that's too much work to do manually.

**Comment by josevalim** [comment]
GitHub has canned replies, so it is three clicks. :)

**Pull request merged**
