### PR TITLE
Build XLA tar

### PR DESCRIPTION
**Pull request by seanmor5**
Moving towards shipping precompiled dependencies to drastically lower NIF build times.

With this version, we'd build and release archives for different architectures and accelerators. Compilation of the NIF would take place on the target machine. Currently there are a few issues:

1) The install headers rule includes a LOT of headers, and I'm not really sure how licensing works out if we are to package them all into our repo.

2) The new build process requires an additional `libprotobuf-dev` dependency to be installed. It's available on most package managers, but I'm currently troubleshooting issues with protobuf includes not being found in include paths.

3) I'm not sure exactly how we should differentiate between the dev build process and regular NIF build process

### CODE REVIEW

**Comment by seanmor5** [comment]
Of note, for contributors, we need a way to:

- Build the `xla_extension` target
- Extract the extension to some directory
- Target the extension `lib` and `include` directories

In my current environment, I extracted `xla_extension` to `/usr/local/` and moved `libxla_extension.so` to `/usr/local/xla_extension/lib`

**Comment by josevalim** [comment]
Exciting work!

> In my current environment, I extracted xla_extension to /usr/local/ and moved libxla_extension.so to /usr/local/xla_extension/lib

I would keep them in a separate directory for now, either create a exla/xla_src directory or a new directory at the root called xla. And then soon we will find a way to get those precompiled and installed via Hex.pm? :) But without needing a system install.

**Comment by joelberkeley** [comment]
Would this tar be suitable for other projects? For example, I'm trying, very slowly, to get a minimal XLA library together for use in my project.

**Comment by seanmor5** [comment]
@joelberkeley Our goal with this PR is to work towards having a separate repository which packages a shared object and the relevant headers into a tarball which can be downloaded and linked to a separate project without needing to compile XLA inside the TensorFlow monorepo - this will hopefully save a lot of time and effort.

As far as your question, we plan to maintain this specifically for our project; however, it will probably include all of the dependencies and headers you need to include in your own project so it would probably be suitable enough for you to fork for your own work. I haven't validated this approach works yet as I've been running in to some dependency issues with GRPC.

If you are having problems building XLA for your project, you can feel free to reach out to me. It took me awhile to get XLA to build and integrate with Elixir because of how tightly it's integrated with TensorFlow, but I can probably point you in the right direction for your project

**Comment by joelberkeley** [comment]
Thanks @seanmor5 that's really helpful. I'll wait to see how this work goes, then may reach out to you after, with the email address on your profile

**Comment by seanmor5** [comment]
Progress has been moved to: https://github.com/elixir-nx/xla/pull/1

**Pull request closed without merging**
