### PR TITLE
Add square

### PR DESCRIPTION
**Pull request by krstopro**
Adding `square` that squares the elements of a tensor. I find it convenient to use with pipeline operator `|>` instead of `Nx.pow(2)`.

### CODE REVIEW

**Comment by josevalim** [comment]
I am unsure we need more shortcuts but I'd like to hear everyone's opinion. :)

**Comment by polvalente** [comment]
I don't think `square` is a particularly good one, because of the clash with `Nx.LinAlg.matrix_power(.., 2)`, which is also a "square" of a matrix, but in a matrix multiplication sense.

**Comment by polvalente** [comment]
There's also the issue with complex numbers, where in general things that "square" for reals tend to become `multiply(z, conjugate(z))` for complex

**Comment by josevalim** [comment]
It seems best to avoid this one in particular then. Thanks @krstopro !

**Pull request closed without merging**
