### PR TITLE
Remove unused device api

### PR DESCRIPTION
**Pull request by josevalim**

### CODE REVIEW

**Review by polvalente — APPROVED** [review]
Aren't there any tests to remove?

**Comment by josevalim** [comment]
@polvalente nope.

**Comment by seanmor5** [comment]
@josevalim So I think we are going to end up needing these in a multi-device setting when we get there. We can remove for now, but it will probably end up getting reintroduced later

**Comment by josevalim** [comment]
@seanmor5 I think last time we talked it seems we could stick with using the device_id exclusively. But yeah, we can add this back if necessary. :)

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Pull request merged**
