### PR TITLE
Add grad tests for Nx.window_sum, Nx.pad, and Nx.put_slice

### PR DESCRIPTION
**Pull request by Benjamin-Philip**
See #695.

### CODE REVIEW

**Comment by Benjamin-Philip** [comment]
I've not added an imaginary part in the left hand side as they don't seem to make a difference to the rhs (at least for pad and put_slice).

**Comment by polvalente** [comment]
> I've not added an imaginary part in the left hand side as they don't seem to make a difference to the rhs (at least for pad and put_slice).

@Benjamin-Philip could you multiply the tensors by Nx.Constants.i()? Just so we ensure they are well behaved for imaginary tensors.

**Comment by Benjamin-Philip** [comment]
> > I've not added an imaginary part in the left hand side as they don't seem to make a difference to the rhs (at least for pad and put_slice).
> 
> @Benjamin-Philip could you multiply the tensors by Nx.Constants.i()? Just so we ensure they are well behaved for imaginary tensors.

I've multiplied all the tensors by `i`, but now the real part is zero. I hope that's okay? Or should I rewrite the tests to have a non-zero real and imaginary part?

**Comment by polvalente** [comment]
> > > I've not added an imaginary part in the left hand side as they don't seem to make a difference to the rhs (at least for pad and put_slice).
> > 
> > @Benjamin-Philip could you multiply the tensors by Nx.Constants.i()? Just so we ensure they are well behaved for imaginary tensors.
> 
> I've multiplied all the tensors by `i`, but now the real part is zero. I hope that's okay? Or should I rewrite the tests to have a non-zero real and imaginary part?

I think it's ok that they are purely imaginary :)

**Review by polvalente — APPROVED** [review]

**Pull request merged**
