### PR TITLE
Adding the Upsample layer support to AxonOnnx.Deserialize

### PR DESCRIPTION
**Pull request by stefkohub**
In order to start working on adding upsample layer type support for AxonOnnx, I started adding the interpolate Libtorch function (which is the current function superseding the upsample one).
So I added some new code trying to follow as much as possible the code style and function conventions.
Next steps will be:
1. add this somewhere into Nx (Maybe into Nx.LinAlg?) 
2. create the function into Axon.Deserialize

Are you interested into this functionality?

### CODE REVIEW

**Comment by josevalim** [comment]
Hi @stefkohub! We are definitely interested in this, but our approach to adding new functions has been slightly different:

1. First we must implement those functions with pure Nx on top of the existing primitives
2. This means non-optimized versions will be available for all backends/compilers
3. Then we can add backend specific optimizations, but this requires #362 which I am to prioritize

Does that make sense?

That said, we would really appreciate help with step 1. Perhaps we can leave this open and revisit once step 1 and #362 are complete?

**Comment by seanmor5** [comment]
My opinion is that this is too specific to Axon to include here. A libtorch implementation would be useful for those wanting to use libtorch but that would need to be included as a custom call. I have a draft upsample PR that partially implements this functionality. It is possible purely in defn which is the route I would go so it's not backend specific.

**Comment by josevalim** [comment]
I am wondering how we can navigate these waters in the long term though. If we want to optimize it for Torchx, then we need to have specified as part of the backend? Unless we let Axon tell the Torchx specific implementation, but then Torchx concerns start leaking into Axon.

Perhaps we should start by benchmarking the pure Nx with the Torchx specific implementation? Maybe upscale is implemented on top of existing primitives in Torchx and there won't be such a large difference after all...

**Comment by stefkohub** [comment]
Hi all, and thank you for your answers!
Yes that's a Torchx specific implementation since that's the quickest solution I found to obtain a tensor upsample/downsample functionality. I am still learning the great job you all have done since now, and now I am better understanding the approach and priorities.
Since @seanmor5 is already working on an upsample layer in Nx I think I'll wait for the PR and I'll try to help improving its solution.
So I agree with you @josevalim, please leave this open until the #362 and the native upsample PR are available.
The benchmarking proposal is quite interesting. Maybe some functionalities (pure Nx or coming from any other library) have different performances than the expected and will drive some choices.

**Comment by loretoparisi** [comment]
> I am wondering how we can navigate these waters in the long term though. If we want to optimize it for Torchx, then we need to have specified as part of the backend? Unless we let Axon tell the Torchx specific implementation, but then Torchx concerns start leaking into Axon.
> 
> 
> 
> Perhaps we should start by benchmarking the pure Nx with the Torchx specific implementation? Maybe upscale is implemented on top of existing primitives in Torchx and there won't be such a large difference after all...

At the end of the day, `libtorch` is the best option for deep learning. From keras back and forth within Tensorflow we have learned a lot of things...
I would see a fully fledged axon Torch backend, so I vote for a specific Torchx implementation and optimization for Nx!

**Comment by seanmor5** [comment]
@stefkohub It seems that ONNX Upsample is deprecated in favor of Resize. I've started implementing `Axon.Layers.resize` to support the Resize operator in AxonOnnx. Will that work for your use case?

**Comment by stefkohub** [comment]
Hi @seanmor5, that's new for me too. I just read about it now and it seems the Resize operator is a superset of the Upsample. So I just need to understand how this new operator woks and modify my darknet_to_onnx code to create an Onnx model using Resize layer instead of Upsample ones... And then wait for your new code to import it into an AxonOnnx model. Thank you!

**Comment by seanmor5** [comment]
I believe this has been addressed now as `resize` is apart of Axon and Upsample has been added to AxonOnnx. We can reevaluate adding a `resize` to the Nx API later.

**Pull request closed without merging**
